name: "PR Metadata Action"
description: "Add pull request file changes as a comment to a newly created PR"

inputs:
  owner:
    description: "The owner of the repo"
    required: true
  repo:
    description: "The name of the repo"
    required: true
  pr_number:
    description: "The number of the new PR"
    required: true
  token:
    description: "The token to use to access the GH API"
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
