name: Pull Request Assigner

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  assigner:
    runs-on: ubuntu-latest
    name: Assign
    steps:
      - name: Assign
        uses: anderzaj/pr-metadata-action@master
        with:
          pr-number: ${{ github.event.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: ".github/assign_reviewers.yml"
