name: Pull Request Assigner

on:
  pull_request:
    types: [opened, reopened]

jobs:
  assigner:
    runs-on: ubuntu-latest
    name: Assign
    steps:
      - name: Assign
        uses: anderzaj/pull-request-assigner@fix/undefined-unavailable-users
        with:
          configuration-path: ".github/assign_reviewers.yml"
